title: My blog
description: UET-VNU
author: "Đinh Xuân Hùng"


theme: minima

# Minima social links

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/home.md
  - _pages/contact.md
  - _pages/blog.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
